# Generated by Django 5.2 on 2025-04-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255, verbose_name="place")),
                ("time", models.TimeField(verbose_name="time")),
                ("action", models.CharField(max_length=255, verbose_name="action")),
                ("pleasant", models.BooleanField(verbose_name="pleasant")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("week", "Каждую неделю"),
                            ("day", "Каждый день"),
                            ("month", "Каждый месяц"),
                        ],
                        default="day",
                        max_length=30,
                        verbose_name="periodicity",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reward"
                    ),
                ),
                ("lead_time", models.DurationField(verbose_name="lead time")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="public"),
                ),
                (
                    "related",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habit",
                        to="habit.habit",
                        verbose_name="related",
                    ),
                ),
            ],
        ),
    ]
