# Generated by Django 5.2 on 2025-04-21 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("week", "Каждую неделю"),
                    ("day", "Каждый день"),
                    ("2 days", "Каждые 2 дня"),
                    ("3 days", "Каждые 3 дня"),
                ],
                default="day",
                max_length=30,
                verbose_name="periodicity",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
