# Generated by Django 5.2 on 2025-04-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit", "0003_alter_habit_periodicity_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("3 days", "Каждые 3 дня"),
                    ("day", "Каждый день"),
                    ("2 days", "Каждые 2 дня"),
                    ("week", "Каждую неделю"),
                ],
                default="day",
                max_length=30,
                verbose_name="periodicity",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habit",
                to="habit.habit",
                verbose_name="related",
            ),
        ),
    ]
