# Generated by Django 5.2 on 2025-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit", "0004_alter_habit_periodicity_alter_habit_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("day", "Каждый день"),
                    ("week", "Каждую неделю"),
                    ("3 days", "Каждые 3 дня"),
                    ("2 days", "Каждые 2 дня"),
                ],
                default="day",
                max_length=30,
                verbose_name="periodicity",
            ),
        ),
    ]
